/**
 * StringParseException.java
 *
 * This file was generated by MapForce 2017r3.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package org.assimbly.edifactcommon.types;


public class StringParseException extends SchemaTypeException {
  int position;

  public StringParseException(String text, int newposition) {
    super(text);
    position = newposition;
  }

  public StringParseException(Exception other) {
    super(other);
  }
}
