////////////////////////////////////////////////////////////////////////
//
// MappingException.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package org.assimbly.edifactcommon.text.tablelike;

public class MappingException extends Exception {
    public MappingException(String message) {
        super(message);
    }

    public MappingException(String message, Exception innerexception) {
        super(message, innerexception);
    }
}