////////////////////////////////////////////////////////////////////////
//
// RecordBasedParser.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package org.assimbly.edifactcommon.text.tablelike;

public abstract class RecordBasedParser {
    private IRecordBasedParserObserver m_Observer = null;

    public IRecordBasedParserObserver getObserver() {
        return m_Observer;
    }

    public void setObserver(IRecordBasedParserObserver rhs) {
        m_Observer = rhs;
    }

    public abstract int parse(String buffer) throws MappingException;

    protected void notifyAboutRecordFound(String[] fields) {
        if (null != m_Observer)
            m_Observer.notifyAboutRecordFound(new Record(fields));
    }

    protected void notifyAboutRecordFound(StringList fields) {
        if (null != m_Observer)
            m_Observer.notifyAboutRecordFound(new Record(fields));
    }
}