////////////////////////////////////////////////////////////////////////
//
// EDITRADACOMSSettings.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package org.assimbly.edifactcommon.text.edi;

public class EDITradacomsSettings extends EDISettings {

	public EDITradacomsSettings()
	{
		super.mEDIStandard = EDIStandard.EDITRADACOMS;
	}	
	
}
