////////////////////////////////////////////////////////////////////////
//
// ColumnDelimited.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package world.dovetail.edifactcommon.text.flex;

public class ColumnDelimited {
	public Command next;
	public String name;

	public ColumnDelimited(Command next, String name) {
		this.next = next;
		this.name = name;
	}
}
