////////////////////////////////////////////////////////////////////////
//
// SplitAtDelimiterLineStartsWithMultipleRegex.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package world.dovetail.edifactcommon.text.flex;

public class SplitAtDelimiterLineStartsWithMultipleRegex extends SplitAtDelimiterLineStartsWithRegex {
	public SplitAtDelimiterLineStartsWithMultipleRegex( String pattern, boolean matchcase ) {
		super( pattern, matchcase );
		consumeFirstLine = true;
	}
}
