////////////////////////////////////////////////////////////////////////
//
// Table.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package org.assimbly.edifactcommon.text.tablelike.flf;

import org.assimbly.edifactcommon.text.tablelike.ColumnSpecification;
import org.assimbly.edifactcommon.text.tablelike.Header;
import org.assimbly.edifactcommon.text.tablelike.ISerializer;
import org.assimbly.edifactcommon.typeinfo.MemberInfo;
import org.assimbly.edifactcommon.typeinfo.TypeInfo;

public class Table extends org.assimbly.edifactcommon.text.tablelike.Table
{
	private int m_lineEnd = 0;

	public Table(TypeInfo tableType, int lineEnd)
	{
		super(false);
		this.tableType = tableType;
		this.m_lineEnd = lineEnd;
		init();
	}

	public Format getFormat() { return ((Serializer) m_Serializer).getFormat(); }

	protected ISerializer createSerializer()
	{
		return new Serializer(this,m_lineEnd);
	}

	private static int getLength(MemberInfo member)
	{
		TypeInfo ti = member.getDataType();
		if (ti.facets != null)
        {
    		for( int iFacet = 0 ; iFacet < ti.facets.length ; ++iFacet )
    		{
    			if (ti.facets[iFacet].facetName.equals("length") || ti.facets[iFacet].facetName.equals("maxLength"))
    				return ti.facets[iFacet].intValue; 
    		}
        }
		return Integer.MAX_VALUE;
	}

	protected void initHeader(Header header)
	{
		for( int iMember = 0 ; iMember < tableType.getMembers().length ; ++iMember )
		{
			MemberInfo member = tableType.getMembers()[iMember];
			header.add(
				new ColumnSpecification(member.getLocalName(), getLength(member.getDataType().getMembers()[0])));
		}
	}
}
