////////////////////////////////////////////////////////////////////////
//
// CommandBlock.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package org.assimbly.edifactcommon.text.flex;

import org.assimbly.edifactcommon.text.ITextNode;
import org.assimbly.edifactcommon.text.TextNodeList;

public class CommandBlock extends Command {
	public CommandBlock(String name) {
		super(name);
	}
	
	public boolean readText(DocumentReader doc) {
		doc.getOutputTree().enterElement(getName(), ITextNode.Group);
		super.readText(doc);
		doc.getOutputTree().leaveElement(getName());
		return true;
	}
	
	public boolean writeText(DocumentWriter doc) {
		TextNodeList children = doc.getCurrentNode().getChildren().filterByName(getName());
		for (int i = 0; i < children.size(); ++i)
		{
			StringBuffer restStr = new StringBuffer();
			DocumentWriter restDoc = new DocumentWriter(children.getAt(i), restStr, doc.getLineEnd());
			super.writeText(restDoc);
			doc.appendText(restStr);
		}
		return true;
	}
}
