////////////////////////////////////////////////////////////////////////
//
// DocumentWriter.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package org.assimbly.edifactcommon.text.flex;

import org.assimbly.edifactcommon.text.ITextNode;

public class DocumentWriter implements Appender {
	private ITextNode current;
	private StringBuffer content;
	private int lineEnd;
	
	public DocumentWriter(ITextNode tree, StringBuffer buff, int lineEnd) {
		this.content = buff;
		this.current = tree;
		this.lineEnd = lineEnd;
	}

	public int getLineEnd() {
		return lineEnd;
	}

	public ITextNode getCurrentNode() {
		return current;
	}
	
	public void appendText(String text) {
		content.append(text);
	}
	
	public void appendText(StringBuffer text) {
		content.append(text.toString());
	}

	public void appendLineEnd() {
		String s = switch(lineEnd)
		{
			case 0 -> System.getProperty("line.separator");
			case 1 -> "\r\n";
			case 2 -> "\n";
			case 3 -> "\r";
			default -> "\r\n";
		};
		
		content.append(s);
	}
}
