////////////////////////////////////////////////////////////////////////
//
// SplitAtDelimiterLineStartsWithMultiple.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package org.assimbly.edifactcommon.text.flex;

public class SplitAtDelimiterLineStartsWithMultiple extends SplitAtDelimiterLineStartsWith {
	public SplitAtDelimiterLineStartsWithMultiple(String delimiter) {
		super(delimiter);
		consumeFirstLine = true;
	}
}
