/**
 * XmlException.java
 *
 * This file was generated by MapForce 2017r3.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package world.dovetail.edifactcommon.xml;


import world.dovetail.edifactcommon.AltovaException;

public class XmlException extends AltovaException {
	public XmlException(String text) {
		super(text);
	}

	public XmlException(Exception other) {
		super(other);
	}
}
