/**
 * NotANumberException.java
 *
 * This file was generated by MapForce 2017r3.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package world.dovetail.edifactcommon.types;


public class NotANumberException extends SchemaTypeException {
  public NotANumberException(String text) {
    super(text);
  }

  public NotANumberException(Exception other) {
    super(other);
  }
}
