package world.dovetail.amazon.domain;

public enum Operation {
    LIST_MARKETPLACE_PARTICIPATIONS, SUBMIT_FEED, GET_FEED_SUBMISSION_RESULT, LIST_ORDERS, LIST_ORDER_ITEMS,
    GET_REPORT_LIST, GET_REPORT, UPDATE_REPORT_ACKNOWLEDGEMENTS
}
