/**
 * TargetInstanceUnavailableException.java
 *
 * This file was generated by MapForce 2017r3.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package world.dovetail.edifactcommon;


public class TargetInstanceUnavailableException extends RuntimeException
{

	public TargetInstanceUnavailableException(String text)
	{
		super(text);
	}

	public TargetInstanceUnavailableException(String text, Throwable other)
	{
		super(text, other);
	}

}
