/**
 * TraceProvider.java
 *
 * This file was generated by MapForce 2017r3.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */


package world.dovetail.edifactcommon;


public abstract class TraceProvider {
	protected TraceTarget traceTarget = null;

	protected void writeTrace(String info) {
		if (traceTarget != null)
			traceTarget.writeTrace(info);
	}

	public void registerTraceTarget(TraceTarget newTraceTarget) {
		traceTarget = newTraceTarget;
	}

	public void unregisterTraceTarget() {
		traceTarget = null;
	}
}
