////////////////////////////////////////////////////////////////////////
//
// BaseType.java
//
// This file was generated by MapForce 2017r3.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package world.dovetail.edifactcommon.text;

public class BaseType {
	protected ITextNode m_Node = null;

	public ITextNode getNode() {
		return m_Node;
	}

	public BaseType(ITextNode node) {
		m_Node = node;
	}
}