name: Release Snapshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  delete_old_snapshots:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.custom-components
            org.assimbly.smooksnoxml
            org.assimbly.auth
            org.assimbly.aggregate
            org.assimbly.aleris
            org.assimbly.amazon
            org.assimbly.archive
            org.assimbly.cookies
            org.assimbly.csvtoxml
            org.assimbly.docconverter
            org.assimbly.edi
            org.assimbly.edifact
            org.assimbly.edifactcommon
            org.assimbly.edifactdotweb
            org.assimbly.edifactstandards
            org.assimbly.encoder
            org.assimbly.enrich
            org.assimbly.exceltoxml
            org.assimbly.flv
            org.assimbly.fmuta

      - name: Delete older snapshots 2
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: assimbly
          type: maven
          keep: 0
          version-pattern: "^\\S+\\-SNAPSHOT$"
          names: |
            org.assimbly.formtoxml
            org.assimbly.googledrive
            org.assimbly.hl7
            org.assimbly.mail
            org.assimbly.multipart
            org.assimbly.oauth2token
            org.assimbly.pdf
            org.assimbly.pdftotext
            org.assimbly.replace
            org.assimbly.sandbox
            org.assimbly.simplereplace
            org.assimbly.smb
            org.assimbly.soap
            org.assimbly.sql
            org.assimbly.tenantvariables
            org.assimbly.throttling            
            org.assimbly.xmltocsv
            org.assimbly.xmltoexcel
            org.assimbly.xmltojson

  call-release-jars:
    needs: delete_old_snapshots
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      branch: 'develop'
