name: Finish Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

  workflow_call:
    inputs:
      branch:
        description: 'Branch to use'
        default: 'develop'
        type: string
      milestone:
        description: 'Milestone to use as version'
        type: string

jobs:

  create-new-branch:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          repository: assimbly/custom-components
          ref: "develop"
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: create a new branch
        run: |
          git fetch --all          
          git config --global push.autoSetupRemote true
          git config --local user.email "raymondmeester@gmail.com"
          git config --local user.name "skin27"
          git checkout -b ${{inputs.milestone}}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          repository: assimbly/custom-components
          branch: ${{ inputs.milestone }}
          force_with_lease: true


  call-update-version:
    needs: create-new-branch
    uses: ./.github/workflows/update-version.yml
    secrets: inherit
    with:
      branch: "${{ inputs.milestone }}"
      milestone: "${{ inputs.milestone }}"

  merge-new-branch:

    needs: call-update-version
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          repository: assimbly/custom-components
          ref: ${{ inputs.milestone }}
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Merge release to main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ inputs.milestone }}
          target_branch: main
          message: "Release ${{ inputs.milestone }}"
          github_token: ${{ secrets.RELEASE_TOKEN }}

  delete-old-packages:

    needs: merge-new-branch
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Delete older snapshots
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: assimbly
          type: maven
          keep: 0
          token: ${{ secrets.MAVEN_TOKEN }}
          semver-pattern: ${{ inputs.milestone }}
          names: |
            org.assimbly.custom-components
            org.assimbly.smooksnoxml
            org.assimbly.auth
            org.assimbly.aggregate
            org.assimbly.aleris
            org.assimbly.amazon
            org.assimbly.archive
            org.assimbly.cookies
            org.assimbly.csvtoxml
            org.assimbly.docconverter
            org.assimbly.edi
            org.assimbly.edifact
            org.assimbly.edifactcommon
            org.assimbly.edifactdotweb
            org.assimbly.edifactstandards
            org.assimbly.encoder
            org.assimbly.enrich
            org.assimbly.exceltoxml
            org.assimbly.flv
            org.assimbly.fmuta

      - name: Delete older snapshots 2
        uses: smartsquaregmbh/delete-old-packages@v0.7.0
        with:
          organization: assimbly
          type: maven
          keep: 0
          token: ${{ secrets.MAVEN_TOKEN }}
          semver-pattern: ${{ inputs.milestone }}
          names: |
            org.assimbly.formtoxml
            org.assimbly.googledrive
            org.assimbly.hl7
            org.assimbly.mail
            org.assimbly.multipart
            org.assimbly.oauth2token
            org.assimbly.pdf
            org.assimbly.pdftotext
            org.assimbly.replace
            org.assimbly.sandbox
            org.assimbly.simplereplace
            org.assimbly.smb
            org.assimbly.soap
            org.assimbly.sql
            org.assimbly.throttling            
            org.assimbly.xmltocsv
            org.assimbly.xmltoexcel
            org.assimbly.xmltojson

  call-release-jars:
    needs: delete-old-packages
    uses: ./.github/workflows/release-jars.yml
    secrets: inherit
    with:
      branch: 'main'