name: Release Jars

on:
  workflow_dispatch:
  workflow_call:

jobs:
  publish_jar:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: "${{ github.ref_name }}"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20

        with:

          repositories: >
            [
                {
                  "id": "maven",
                  "name": "Maven Central",
                  "url": "https://repo1.maven.org/maven2"
                },
                {
                  "id": "github",
                  "name": "Assimbly Base Repository",
                  "url": "https://maven.pkg.github.com/assimbly/base",
                  "snapshots": {
                    "enabled": "true"
                  }
                },
                {
                    "id": "aurea",
                    "name": "Aurea Sonic Repository",
                    "url": "https://int-factory.aurea.com/nexus/content/repositories/sonic-releases/"
                }
            ]
          servers: >
            [
                {
                    "id": "github",
                    "username": "assimbly",
                    "password": "${{ secrets.GITHUB_TOKEN }}"
                }
            ]

      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}